# Generated by Django 5.0.14 on 2025-09-25 17:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_archivo', models.AutoField(db_column='IdArchivo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100, unique=True)),
                ('url_publica', models.CharField(db_column='URLPublica', max_length=500)),
                ('fecha_subida', models.DateTimeField(db_column='FechaSubida')),
            ],
            options={
                'db_table': 'Archivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(db_column='IdContacto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('telefono', models.CharField(db_column='Telefono', max_length=100, unique=True)),
                ('correo_electronico', models.CharField(blank=True, db_column='CorreoElectronico', max_length=100, null=True, unique=True)),
                ('estado', models.IntegerField(db_column='Estado')),
                ('fecha_creacion', models.DateTimeField(db_column='FechaCreacion')),
            ],
            options={
                'db_table': 'Contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.AutoField(db_column='IdEnvio', primary_key=True, serialize=False)),
                ('fecha_envio', models.DateTimeField(db_column='FechaEnvio')),
                ('estado_envio', models.CharField(db_column='EstadoEnvio', max_length=20)),
                ('twilio_sid', models.CharField(blank=True, db_column='TwilioSID', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Envio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('estadoActividad', models.BooleanField(default=True)),
                ('estadoRecuperacion', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
