
@baseUrl = http://127.0.0.1:8000/api
@archivoId = 1

###
# =============================================
# 1. Obtener TODOS los archivos
# =============================================
GET {{baseUrl}}/archivos/

###
# =============================================
# 2. Buscar archivos por NOMBRE
# =============================================
GET {{baseUrl}}/archivos/?nombre=Informe2_Julio_2025.pdf

###
# =============================================
# 3. Obtener UN archivo por su ID
# =============================================
GET {{baseUrl}}/archivos/{{archivoId}}/

###
# =============================================
# 4. CREAR un nuevo archivo (POST)
# =============================================
# Registra un nuevo archivo en la base de datos.
POST {{baseUrl}}/archivos/
Content-Type: application/json

{
    "URLPublica": "https://drive.google.com/file/d/19DK-1PKn9YcLHM8AG4KeDFQp9JWKZOTG/view?usp=drivesdk"
}

