@baseUrl = http://127.0.0.1:8000/api
@contactoId = 1
@archivoId = 1

###
# =============================================
# 1. CREAR un nuevo registro de envío (POST)
# =============================================
POST {{baseUrl}}/envios/
Content-Type: application/json

{
    "IdContacto": {{contactoId}},
    "IdArchivo": {{archivoId}},
    "EstadoEnvio": "Enviado",
    "TwilioSID": "SMxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}

###
# =============================================
# 2. OBTENER el historial de envíos de un contacto (GET)
# =============================================
GET {{baseUrl}}/contactos/{{contactoId}}/historial/

###
# =============================================
# 1. ENDPOINT PRINCIPAL: ENVIAR INFORME (POST)
# =============================================
# Este endpoint recibe la URL del PDF desde el frontend y orquesta todo el flujo:
# - Registra el archivo en la BD.
# - Envía el mensaje por WhatsApp.
# - Registra el envío en la BD.
POST {{baseUrl}}/enviar-informe/
Content-Type: application/json

{
    "id_contacto": 1033,
    "pdf_url": "https://drive.google.com/file/d/1O5yKGpLL8aAF__XHj8RfWIgSXuyC-JvK/view?usp=drive_link"
}

###
# =============================================
# ENVIAR un mensaje de texto simple (POST)
# =============================================
POST {{baseUrl}}/enviar-mensaje-texto/
Content-Type: application/json

{
    "id_contacto": 1,
    "mensaje": "Hola mundo."
}

